# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/personal_color_extractor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 707)
        MainWindow.setMaximumSize(QtCore.QSize(16777204, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baseVerticalLayout = QtWidgets.QVBoxLayout()
        self.baseVerticalLayout.setObjectName("baseVerticalLayout")
        self.loadLayout = QtWidgets.QHBoxLayout()
        self.loadLayout.setContentsMargins(-1, 0, -1, -1)
        self.loadLayout.setObjectName("loadLayout")
        self.imagePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imagePathLineEdit.setObjectName("imagePathLineEdit")
        self.loadLayout.addWidget(self.imagePathLineEdit)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.loadLayout.addWidget(self.loadButton)
        self.loadImgeFromWebcamButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadImgeFromWebcamButton.setObjectName("loadImgeFromWebcamButton")
        self.loadLayout.addWidget(self.loadImgeFromWebcamButton)
        self.baseVerticalLayout.addLayout(self.loadLayout)
        self.faceImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.faceImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.faceImageLabel.setObjectName("faceImageLabel")
        self.baseVerticalLayout.addWidget(self.faceImageLabel)
        self.personalColorLabel = QtWidgets.QLabel(self.centralwidget)
        self.personalColorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.personalColorLabel.setObjectName("personalColorLabel")
        self.baseVerticalLayout.addWidget(self.personalColorLabel)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.baseVerticalLayout.addWidget(self.pushButton)
        self.baseVerticalLayout.setStretch(1, 1)
        self.baseVerticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.baseVerticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "퍼스널 컬러 찾기"))
        self.loadButton.setText(_translate("MainWindow", "불러오기"))
        self.loadImgeFromWebcamButton.setText(_translate("MainWindow", "사진찍기"))
        self.faceImageLabel.setText(_translate("MainWindow", "이미지를 불러와 주세요"))
        self.personalColorLabel.setText(_translate("MainWindow", "이미지를 불러온 후 \"추출하기\" 버튼을 누르세요."))
        self.pushButton.setText(_translate("MainWindow", "퍼스널 컬러 추출하기"))
