# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal_color_extractor_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.baseHorizontal = QtWidgets.QHBoxLayout()
        self.baseHorizontal.setObjectName("baseHorizontal")
        self.facialRecogResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.facialRecogResultLabel.setObjectName("facialRecogResultLabel")
        self.baseHorizontal.addWidget(self.facialRecogResultLabel)
        self.baseGrid = QtWidgets.QGridLayout()
        self.baseGrid.setObjectName("baseGrid")
        self.rightEyeLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightEyeLabel.setObjectName("rightEyeLabel")
        self.baseGrid.addWidget(self.rightEyeLabel, 1, 1, 1, 1)
        self.leftCheekLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftCheekLabel.setObjectName("leftCheekLabel")
        self.baseGrid.addWidget(self.leftCheekLabel, 0, 0, 1, 1)
        self.rightCheekLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightCheekLabel.setObjectName("rightCheekLabel")
        self.baseGrid.addWidget(self.rightCheekLabel, 0, 1, 1, 1)
        self.leftEyeLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftEyeLabel.setObjectName("leftEyeLabel")
        self.baseGrid.addWidget(self.leftEyeLabel, 1, 0, 1, 1)
        self.leftEyebrowLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftEyebrowLabel.setObjectName("leftEyebrowLabel")
        self.baseGrid.addWidget(self.leftEyebrowLabel, 2, 0, 1, 1)
        self.rightEyebrowLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightEyebrowLabel.setObjectName("rightEyebrowLabel")
        self.baseGrid.addWidget(self.rightEyebrowLabel, 2, 1, 1, 1)
        self.baseHorizontal.addLayout(self.baseGrid)
        self.horizontalLayout_2.addLayout(self.baseHorizontal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "프론 - 퍼스널컬러 추출"))
        self.facialRecogResultLabel.setText(_translate("MainWindow", "TextLabel"))
        self.rightEyeLabel.setText(_translate("MainWindow", "TextLabel"))
        self.leftCheekLabel.setText(_translate("MainWindow", "TextLabel"))
        self.rightCheekLabel.setText(_translate("MainWindow", "TextLabel"))
        self.leftEyeLabel.setText(_translate("MainWindow", "TextLabel"))
        self.leftEyebrowLabel.setText(_translate("MainWindow", "TextLabel"))
        self.rightEyebrowLabel.setText(_translate("MainWindow", "TextLabel"))
