# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 371)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pronLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.pronLogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pronLogoLabel.setObjectName("pronLogoLabel")
        self.verticalLayout.addWidget(self.pronLogoLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 1, 1, 1, 1)
        self.chromebookIDEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.chromebookIDEdit.setEnabled(False)
        self.chromebookIDEdit.setStatusTip("")
        self.chromebookIDEdit.setObjectName("chromebookIDEdit")
        self.gridLayout.addWidget(self.chromebookIDEdit, 0, 1, 1, 1)
        self.chromebookIDLabel = QtWidgets.QLabel(self.centralwidget)
        self.chromebookIDLabel.setObjectName("chromebookIDLabel")
        self.gridLayout.addWidget(self.chromebookIDLabel, 0, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "프론 - 퍼스널 컬러 측정"))
        self.pronLogoLabel.setText(_translate("MainWindow", "LOGO"))
        self.nameEdit.setStatusTip(_translate("MainWindow", "이름을 입력하세요"))
        self.nameEdit.setPlaceholderText(_translate("MainWindow", "이름을 입력하세요"))
        self.chromebookIDEdit.setPlaceholderText(_translate("MainWindow", "크롬북 ID가 표시됩니다"))
        self.chromebookIDLabel.setText(_translate("MainWindow", "크롬북 ID"))
        self.nameLabel.setText(_translate("MainWindow", "이름"))
        self.startButton.setText(_translate("MainWindow", "시작하기"))
